// This file is autogenerated from build.rs
pub type Precision = f64;
use crate::types::WeibullDist;
pub type Dist = WeibullDist<Precision>;
pub const L: usize = 20;
pub const N_THREADS: usize = 12;
pub const N_TRIES: usize = 2000;
pub const N_RES: usize = (L-1)*(L-2)+L*(L-2) + 2*L;
pub const N_UNK: usize = L * (L - 2);
