// This file is autogenerated from build.rs
use f256::f256;
pub type Precision = f256;
pub const L: usize = 35;
pub const N_THREADS: usize = 11;
pub const N_TRIES: usize = 200;
pub const N_RES: usize = (L-1)*(L-2)+L*(L-2) + 2*L;
pub const N_UNK: usize = L * (L - 2);
